### ISSUE TITLE
Illegal argument in isolate message: Library:'dart:ui'

### ISSUE THREAD

**Issue by matisiekpl** [rorystephenson/flutter_map_supercluster#2] opened 2023-01-27 12:15 UTC
Hello,
I'm getting following error:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:ui' Class: EngineLayer)
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:399:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:379:7)
#2      Isolate.run (dart:isolate:238:15)
#3      compute (package:flutter/src/foundation/_isolates_io.dart:18:18)
#4      compute (package:flutter/src/foundation/isolates.dart:76:19)
#5      _SuperclusterLayerState._initializeClusterManager.<anonymous closure> (package:flutter_map_supercluster/src/layer/supercluster_layer.dart:339:15)
<asynchronous suspension>
```

What should I do?
Deps:
```
  cupertino_icons: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  vector_map_tiles: ^3.1.4
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.1
  flutter_map_location_marker: ^5.1.0+1
  flutter_svg: ^1.1.2
  http: ^0.13.5
  maps_launcher: ^2.0.1
  url_launcher: ^6.1.5
  flutter_map_dragmarker: ^4.1.2
  cross_fade: ^0.3.1
  connectivity_plus: ^3.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_map_supercluster: ^2.2.0
```

Flutter version:
```
environment:
  sdk: '>=2.18.0-257.0.dev <3.0.0'
```

**Comment by rorystephenson** [comment] 2023-01-28 22:13
Hi @matisiekpl,

Can you please share a minimal reproducible example?

**Comment by rorystephenson** [comment] 2023-02-08 10:55
Closing for lack of a reproducible example. If you can provide one I'm happy to have a look.

**Comment by Pepslee** [comment] 2023-03-11 07:55
I have the same problem when use iverpod provider inside Cluster widget.
But wrapIndexCreation: (superclusterConfig) async => createSupercluster(superclusterConfig) solve the issue.
I think the problem is that the cluster widget builds inside an isolate and if I use any provider inside the cluster widget build method it throw an error.

**Comment by rorystephenson** [comment] 2023-03-11 16:20
@Pepslee Ahhhh nice spotting. I am going to re-open and have a better look when I get a chance since widgets should not be getting built in another isolate.

**Comment by rorystephenson** [comment] 2023-04-03 10:53
@Pepslee from a quick look it seems to me that with the default supercluster creation (in an isolate) it should only give an error if the `clusterDataExtractor` includes code which cannot be run in an isolate (e.g. riverpod/provider code). Can you confirm that your `clusterDataExtractor` contains riverpod/provider code? In that case I can update the documentation to explain how to avoid the issue.

**Comment by LamaAgent** [comment] 2023-04-16 18:25
I have the same problem and get the same error message, any solution?

**Comment by rorystephenson** [comment] 2023-04-23 10:50
@LamaAgent by default the clusters are built in a separate isolate to avoid blocking the main isolate. This means that any code in the `clusterDataExtractor` will run in a separate isolate and therefore things like riverpod will not work. You have two options:

1. Refactor your code so that riverpod or other code which can not be run in a separate isolate is not used in the `clusterDataExtractor`.
2. Build clusters in the main isolate by setting `wrapIndexCreation` to: `(superclusterConfig) async => createSupercluster(superclusterConfig)`

**Closed** 2023-05-08 16:07 UTC
